# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('previewText', models.TextField(blank=True, max_length=260)),
                ('fullText', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('\u0414\u0435\u0442\u0438', '\u0414\u0435\u0442\u0438'), ('\u0412\u0435\u0449\u0438', '\u0412\u0435\u0449\u0438'), ('\u0414\u043e\u0441\u0443\u0433', '\u0414\u043e\u0441\u0443\u0433'), ('\u041f\u0443\u0442\u0435\u0448\u0435\u0441\u0442\u0432\u0438\u044f', '\u041f\u0443\u0442\u0435\u0448\u0435\u0441\u0442\u0432\u0438\u044f')], default=b'CH', max_length=40)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
