# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Дети', 'Дети'), ('Вещи', 'Вещи'), ('Досуг', 'Досуг'), ('Путешествия', 'Путешествия')], default='CH', max_length=40),
        ),
    ]
