# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 17:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170912_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 9, 12, 17, 12, 58, 405282, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
