# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('posts', '0005_auto_20170912_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Дети', 'Дети'), ('Вещи', 'Вещи'), ('Досуг', 'Досуг'), ('Путешествия', 'Путешествия'), ('Юмор', 'Юмор')], default='CH', max_length=40),
        ),
    ]
